name: BGforge poify/unpoify
description: Updates Gettext POT template from source language, extracts translations from PO files, commits and pushes the files.
branding:
  icon: message-circle
  color: green

inputs:
  poify:
    description: run poify
    default: 'true'
    required: false
  unpoify:
    description: run unpoify
    default: 'true'
    required: false
  commit:
    description: commit and push poify/unpoify results
    default: 'true'
    required: false
  separate_commits:
    description: use separate commits for poify and unpoify, or a single one
    default: 'true'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        env | grep INPUT
        pip3 install -r "$GITHUB_ACTION_PATH/requirements.txt"
        export PATH="$PATH:$GITHUB_ACTION_PATH"
        $GITHUB_ACTION_PATH/gha.sh
      shell: bash
      env:
        INPUT_POIFY: ${{ inputs.poify }}
        INPUT_UNPOIFY: ${{ inputs.unpoify }}
        INPUT_COMMIT: ${{ inputs.commit }}
        INPUT_SEPARATE_COMMITS: ${{ inputs.separate_commits }}
