name: 'BGforge unpoify'
description: 'Extract translations from Gettext PO'
branding:
  icon: 'message-circle'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail        
        pip3 install -r "../../requirements.txt"
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: |
        set -xeu -o pipefail
        action_root="$(realpath $(dirname $(dirname ${{ github.action_path }})))"
        export PATH="$PATH:$action_root"
        ${{ github.action_path }}/unpoify.sh
      shell: bash
