name: 'BGforge poify'
description: 'Updates and commits Gettext POT template'
branding:
  icon: 'message-circle'
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: |
        action_root="$(realpath ../../)"
        pip3 install -r "$action_root/requirements.txt"
        export PATH="$PATH:$action_root"
        echo $PATH
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: |
        export PATH="$PATH:${{ github.action_path }}"
        ${{ github.action_path }}/poify.sh
      shell: bash
