name: 'BGforge poify'
description: 'Updates and commits Gettext POT template'
branding:
  icon: 'message-circle'
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: pwd; ls -la; pip3 install -r requirements.txt
      shell: bash
      working-directory: ${{ github.action_path }}
    - run:
        export PATH="$PATH:${{ github.action_path }}"
        ${{ github.action_path }}/poify.sh
      shell: bash
