name: 'BGforge poify'
description: 'Updates and commits Gettext POT template'
branding:
  icon: 'message-circle'
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail        
        pip3 install -r "../../requirements.txt"
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: |
        set -xeu -o pipefail
        ls -la
        pwd
        action_root="realpath $(dirname $(dirname ${{ github.action_path }}))"
        export PATH="$PATH:$action_root"
        echo $PATH
        ${{ github.action_path }}/poify.sh
      shell: bash
