name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/checkout@v2

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-lin-0  # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Publish to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -xeu -o pipefail
          poetry config.repositories.test-pypi https://test.pypi.org
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry build
          poetry publish -r test-pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
